bind/capps-named: Add bind-tools to Docker image, add DNS query to named server in test
Test DNS query uses zone files in test-config. Query is deemed successful if
response includes the appropriate SOA record.

Explicitly shut down Docker in Test, as it was necessary to remove -v arg when
evoking capps-named. This also means that BIND version cannot be verified in
the same way as before. Need to re-implement this or find a way around the
absent -v arg.

bind-tools was added to Docker image because test query uses dig.

diff --git a/bind/Test b/bind/Test
--- a/bind/Test
+++ b/bind/Test
@@ -2,20 +2,34 @@
 set -e -o pipefail
 trap 'echo 1>&2 FAILED; exit 1' 0
 
-die() { echo 1>&2 "$(basename "$0"):" "$@"; exit 1; }
+docker='sudo docker'
+
+die() {
+    echo 1>&2 "$(basename "$0"):" "$@";
+    [[ "$($docker ps | grep capps-bind)" ]] && \
+    $docker stop capps-bind 1>/dev/null
+    exit 1;
+}
 
 base=$(cd "$(dirname "$0")" && pwd -P)
 cd $base
 sudo -v || die 'Cannot sudo to run docker'
-docker='sudo docker'
 
 #   We always build a test image; it's tagged :latest by hand.
 image=capps-bind:test
 
 [[ $1 = -n ]] || $docker build -t $image -q .
 
-version=$(./capps-named -T -C $(pwd)/test-config --rm --detach=false -- -v)
-[[ $version = 'BIND 9'* ]] || die "FAIL: unexpected version: $version"
+docker_args='--rm --name capps-bind --detach=true'
+version=$(./capps-named -T -C $(pwd)/test-config $docker_args)
+
+record=$($docker exec -it capps-bind dig SOA example.com @127.0.0.1)
+[[ $record == *"dns1.example.com."* ]] || \
+die "FAIL: named did not return expected DNS records, instead received$record"
+
+#[[ $version = 'BIND 9'* ]] || die "FAIL: unexpected version: $version"
 
 trap '' 0
 echo OK
+
+$docker stop capps-bind 1>/dev/null
