bind/capps-named: Run in Python instead of bash
Replace bash script with Python script. The idea is to leverage Python's
abilities to manage Docker containers and DNS processes, and to bring
the DNS server in line with the test client (which is already Python).

Using docker-py to manage Docker processes, and dnspython to manage DNS
server and test client.

Testing no longer requires a .cid file to store the container ID; this
has been removed. The .build folder is now used exlusively by venv. Test
cleanup is handled by docker-py.

As of now, all options for capps-named are hard-coded; the next step is
to re-instate the options which were in the old script. For this reason,
no unit tests have been implemented yet. These too will come later.

diff --git a/bind/Test b/bind/Test
--- a/bind/Test
+++ b/bind/Test
@@ -1,15 +1,9 @@
 #!/usr/bin/env bash
-set -e -o pipefail
-trap 'echo 1>&2 FAILED; exit 1' 0
-docker='sudo docker'
+set -eu -o pipefail
 
 die() {
     echo 1>&2 "$(basename "$0"):" "$@";
     exit 1;
-}
-
-cleanup() {
-    $docker stop $cid 1>/dev/null
 }
 
 base=$(cd "$(dirname "$0")" && pwd -P)
@@ -19,25 +13,17 @@ cd $base
 #pytest -q "$@"
 
 sudo -v || die 'Cannot sudo to run docker'
+py="sudo $base/.build/virtualenv/bin/python3"
 
 #   We always build a test image; it's tagged :latest by hand.
 image=capps-bind:test
 
-[[ $1 = -n ]] || $docker build -t $image -q .
+#pytest -q "$@"
 
-docker_args='--rm --cidfile ./.build/test.cid --detach=true'
-version=$(./capps-named -T -C $(pwd)/tconfig $docker_args)
-cid=$(<$base/.build/test.cid)
-rm -f $base/.build/test.cid
-
-record=$(python test_client.py)
+server=$($py capps-named.py)
+record=$($py test_client.py $server)
 
 [[ $record == *"thisisatextrecord"* ]] || \
-die "FAIL: named did not return expected DNS records, instead received$record"
+die "FAIL: named did not return expected DNS records, instead received $record"
 
-#[[ $version = 'BIND 9'* ]] || die "FAIL: unexpected version: $version"
-
-trap '' 0
 echo OK
-
-trap cleanup EXIT
